// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: service_wishlist.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
[global::ProtoBuf.ProtoContract(Name = @"CWishlist_AddToWishlist_Request")]
public partial class CWishlistAddToWishlistRequest : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"appid")]
    public uint Appid
    {
        get => __pbn__Appid.GetValueOrDefault();
        set => __pbn__Appid = value;
    }
    public bool ShouldSerializeAppid() => __pbn__Appid != null;
    public void ResetAppid() => __pbn__Appid = null;
    private uint? __pbn__Appid;

    [global::ProtoBuf.ProtoMember(2, Name = @"navdata")]
    public CUserInterfaceNavData Navdata { get; set; }

}

[global::ProtoBuf.ProtoContract(Name = @"CWishlist_AddToWishlist_Response")]
public partial class CWishlistAddToWishlistResponse : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"wishlist_count")]
    public uint WishlistCount
    {
        get => __pbn__WishlistCount.GetValueOrDefault();
        set => __pbn__WishlistCount = value;
    }
    public bool ShouldSerializeWishlistCount() => __pbn__WishlistCount != null;
    public void ResetWishlistCount() => __pbn__WishlistCount = null;
    private uint? __pbn__WishlistCount;

}

[global::ProtoBuf.ProtoContract(Name = @"CWishlist_GetWishlist_Request")]
public partial class CWishlistGetWishlistRequest : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"steamid", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public ulong Steamid
    {
        get => __pbn__Steamid.GetValueOrDefault();
        set => __pbn__Steamid = value;
    }
    public bool ShouldSerializeSteamid() => __pbn__Steamid != null;
    public void ResetSteamid() => __pbn__Steamid = null;
    private ulong? __pbn__Steamid;

}

[global::ProtoBuf.ProtoContract(Name = @"CWishlist_GetWishlist_Response")]
public partial class CWishlistGetWishlistResponse : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"items")]
    public global::System.Collections.Generic.List<CWishlistGetWishlistResponseWishlistItem> Items { get; } = new global::System.Collections.Generic.List<CWishlistGetWishlistResponseWishlistItem>();

}

[global::ProtoBuf.ProtoContract(Name = @"CWishlist_GetWishlist_Response_WishlistItem")]
public partial class CWishlistGetWishlistResponseWishlistItem : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"appid")]
    public uint Appid
    {
        get => __pbn__Appid.GetValueOrDefault();
        set => __pbn__Appid = value;
    }
    public bool ShouldSerializeAppid() => __pbn__Appid != null;
    public void ResetAppid() => __pbn__Appid = null;
    private uint? __pbn__Appid;

    [global::ProtoBuf.ProtoMember(2, Name = @"priority")]
    public uint Priority
    {
        get => __pbn__Priority.GetValueOrDefault();
        set => __pbn__Priority = value;
    }
    public bool ShouldSerializePriority() => __pbn__Priority != null;
    public void ResetPriority() => __pbn__Priority = null;
    private uint? __pbn__Priority;

    [global::ProtoBuf.ProtoMember(3, Name = @"date_added")]
    public uint DateAdded
    {
        get => __pbn__DateAdded.GetValueOrDefault();
        set => __pbn__DateAdded = value;
    }
    public bool ShouldSerializeDateAdded() => __pbn__DateAdded != null;
    public void ResetDateAdded() => __pbn__DateAdded = null;
    private uint? __pbn__DateAdded;

}

[global::ProtoBuf.ProtoContract(Name = @"CWishlist_GetWishlistItemCount_Request")]
public partial class CWishlistGetWishlistItemCountRequest : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"steamid", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public ulong Steamid
    {
        get => __pbn__Steamid.GetValueOrDefault();
        set => __pbn__Steamid = value;
    }
    public bool ShouldSerializeSteamid() => __pbn__Steamid != null;
    public void ResetSteamid() => __pbn__Steamid = null;
    private ulong? __pbn__Steamid;

}

[global::ProtoBuf.ProtoContract(Name = @"CWishlist_GetWishlistItemCount_Response")]
public partial class CWishlistGetWishlistItemCountResponse : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"count")]
    public uint Count
    {
        get => __pbn__Count.GetValueOrDefault();
        set => __pbn__Count = value;
    }
    public bool ShouldSerializeCount() => __pbn__Count != null;
    public void ResetCount() => __pbn__Count = null;
    private uint? __pbn__Count;

}

[global::ProtoBuf.ProtoContract(Name = @"CWishlist_GetWishlistItemsOnSale_Request")]
public partial class CWishlistGetWishlistItemsOnSaleRequest : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"context")]
    public StoreBrowseContext Context { get; set; }

    [global::ProtoBuf.ProtoMember(2, Name = @"data_request")]
    public StoreBrowseItemDataRequest DataRequest { get; set; }

}

[global::ProtoBuf.ProtoContract(Name = @"CWishlist_GetWishlistItemsOnSale_Response")]
public partial class CWishlistGetWishlistItemsOnSaleResponse : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"items")]
    public global::System.Collections.Generic.List<CWishlistGetWishlistItemsOnSaleResponseWishlistItem> Items { get; } = new global::System.Collections.Generic.List<CWishlistGetWishlistItemsOnSaleResponseWishlistItem>();

}

[global::ProtoBuf.ProtoContract(Name = @"CWishlist_GetWishlistItemsOnSale_Response_WishlistItem")]
public partial class CWishlistGetWishlistItemsOnSaleResponseWishlistItem : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"appid")]
    public uint Appid
    {
        get => __pbn__Appid.GetValueOrDefault();
        set => __pbn__Appid = value;
    }
    public bool ShouldSerializeAppid() => __pbn__Appid != null;
    public void ResetAppid() => __pbn__Appid = null;
    private uint? __pbn__Appid;

    [global::ProtoBuf.ProtoMember(2, Name = @"store_item")]
    public StoreItem StoreItem { get; set; }

}

[global::ProtoBuf.ProtoContract(Name = @"CWishlist_GetWishlistSortedFiltered_Request")]
public partial class CWishlistGetWishlistSortedFilteredRequest : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"steamid", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public ulong Steamid
    {
        get => __pbn__Steamid.GetValueOrDefault();
        set => __pbn__Steamid = value;
    }
    public bool ShouldSerializeSteamid() => __pbn__Steamid != null;
    public void ResetSteamid() => __pbn__Steamid = null;
    private ulong? __pbn__Steamid;

    [global::ProtoBuf.ProtoMember(2, Name = @"context")]
    public StoreBrowseContext Context { get; set; }

    [global::ProtoBuf.ProtoMember(3, Name = @"data_request")]
    public StoreBrowseItemDataRequest DataRequest { get; set; }

    [global::ProtoBuf.ProtoMember(4, Name = @"sort_order")]
    [global::System.ComponentModel.DefaultValue(0)]
    public int SortOrder
    {
        get => __pbn__SortOrder ?? 0;
        set => __pbn__SortOrder = value;
    }
    public bool ShouldSerializeSortOrder() => __pbn__SortOrder != null;
    public void ResetSortOrder() => __pbn__SortOrder = null;
    private int? __pbn__SortOrder;

    [global::ProtoBuf.ProtoMember(5, Name = @"filters")]
    public CWishlistFilters Filters { get; set; }

    [global::ProtoBuf.ProtoMember(6, Name = @"start_index")]
    [global::System.ComponentModel.DefaultValue(0)]
    public int StartIndex
    {
        get => __pbn__StartIndex ?? 0;
        set => __pbn__StartIndex = value;
    }
    public bool ShouldSerializeStartIndex() => __pbn__StartIndex != null;
    public void ResetStartIndex() => __pbn__StartIndex = null;
    private int? __pbn__StartIndex;

    [global::ProtoBuf.ProtoMember(7, Name = @"page_size")]
    [global::System.ComponentModel.DefaultValue(100)]
    public int PageSize
    {
        get => __pbn__PageSize ?? 100;
        set => __pbn__PageSize = value;
    }
    public bool ShouldSerializePageSize() => __pbn__PageSize != null;
    public void ResetPageSize() => __pbn__PageSize = null;
    private int? __pbn__PageSize;

}

[global::ProtoBuf.ProtoContract(Name = @"CWishlist_GetWishlistSortedFiltered_Response")]
public partial class CWishlistGetWishlistSortedFilteredResponse : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"items")]
    public global::System.Collections.Generic.List<CWishlistGetWishlistSortedFilteredResponseWishlistItem> Items { get; } = new global::System.Collections.Generic.List<CWishlistGetWishlistSortedFilteredResponseWishlistItem>();

}

[global::ProtoBuf.ProtoContract(Name = @"CWishlist_GetWishlistSortedFiltered_Response_WishlistItem")]
public partial class CWishlistGetWishlistSortedFilteredResponseWishlistItem : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"appid")]
    public uint Appid
    {
        get => __pbn__Appid.GetValueOrDefault();
        set => __pbn__Appid = value;
    }
    public bool ShouldSerializeAppid() => __pbn__Appid != null;
    public void ResetAppid() => __pbn__Appid = null;
    private uint? __pbn__Appid;

    [global::ProtoBuf.ProtoMember(2, Name = @"priority")]
    public uint Priority
    {
        get => __pbn__Priority.GetValueOrDefault();
        set => __pbn__Priority = value;
    }
    public bool ShouldSerializePriority() => __pbn__Priority != null;
    public void ResetPriority() => __pbn__Priority = null;
    private uint? __pbn__Priority;

    [global::ProtoBuf.ProtoMember(3, Name = @"date_added")]
    public uint DateAdded
    {
        get => __pbn__DateAdded.GetValueOrDefault();
        set => __pbn__DateAdded = value;
    }
    public bool ShouldSerializeDateAdded() => __pbn__DateAdded != null;
    public void ResetDateAdded() => __pbn__DateAdded = null;
    private uint? __pbn__DateAdded;

    [global::ProtoBuf.ProtoMember(4, Name = @"store_item")]
    public StoreItem StoreItem { get; set; }

}

[global::ProtoBuf.ProtoContract(Name = @"CWishlist_RemoveFromWishlist_Request")]
public partial class CWishlistRemoveFromWishlistRequest : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"appid")]
    public uint Appid
    {
        get => __pbn__Appid.GetValueOrDefault();
        set => __pbn__Appid = value;
    }
    public bool ShouldSerializeAppid() => __pbn__Appid != null;
    public void ResetAppid() => __pbn__Appid = null;
    private uint? __pbn__Appid;

}

[global::ProtoBuf.ProtoContract(Name = @"CWishlist_RemoveFromWishlist_Response")]
public partial class CWishlistRemoveFromWishlistResponse : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"wishlist_count")]
    public uint WishlistCount
    {
        get => __pbn__WishlistCount.GetValueOrDefault();
        set => __pbn__WishlistCount = value;
    }
    public bool ShouldSerializeWishlistCount() => __pbn__WishlistCount != null;
    public void ResetWishlistCount() => __pbn__WishlistCount = null;
    private uint? __pbn__WishlistCount;

}

[global::ProtoBuf.ProtoContract()]
public partial class CWishlistFilters : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"macos_only")]
    public bool MacosOnly
    {
        get => __pbn__MacosOnly.GetValueOrDefault();
        set => __pbn__MacosOnly = value;
    }
    public bool ShouldSerializeMacosOnly() => __pbn__MacosOnly != null;
    public void ResetMacosOnly() => __pbn__MacosOnly = null;
    private bool? __pbn__MacosOnly;

    [global::ProtoBuf.ProtoMember(2, Name = @"steamos_linux_only")]
    public bool SteamosLinuxOnly
    {
        get => __pbn__SteamosLinuxOnly.GetValueOrDefault();
        set => __pbn__SteamosLinuxOnly = value;
    }
    public bool ShouldSerializeSteamosLinuxOnly() => __pbn__SteamosLinuxOnly != null;
    public void ResetSteamosLinuxOnly() => __pbn__SteamosLinuxOnly = null;
    private bool? __pbn__SteamosLinuxOnly;

    [global::ProtoBuf.ProtoMember(10, Name = @"only_games")]
    public bool OnlyGames
    {
        get => __pbn__OnlyGames.GetValueOrDefault();
        set => __pbn__OnlyGames = value;
    }
    public bool ShouldSerializeOnlyGames() => __pbn__OnlyGames != null;
    public void ResetOnlyGames() => __pbn__OnlyGames = null;
    private bool? __pbn__OnlyGames;

    [global::ProtoBuf.ProtoMember(11, Name = @"only_software")]
    public bool OnlySoftware
    {
        get => __pbn__OnlySoftware.GetValueOrDefault();
        set => __pbn__OnlySoftware = value;
    }
    public bool ShouldSerializeOnlySoftware() => __pbn__OnlySoftware != null;
    public void ResetOnlySoftware() => __pbn__OnlySoftware = null;
    private bool? __pbn__OnlySoftware;

    [global::ProtoBuf.ProtoMember(12, Name = @"only_dlc")]
    public bool OnlyDlc
    {
        get => __pbn__OnlyDlc.GetValueOrDefault();
        set => __pbn__OnlyDlc = value;
    }
    public bool ShouldSerializeOnlyDlc() => __pbn__OnlyDlc != null;
    public void ResetOnlyDlc() => __pbn__OnlyDlc = null;
    private bool? __pbn__OnlyDlc;

    [global::ProtoBuf.ProtoMember(13, Name = @"only_free")]
    public bool OnlyFree
    {
        get => __pbn__OnlyFree.GetValueOrDefault();
        set => __pbn__OnlyFree = value;
    }
    public bool ShouldSerializeOnlyFree() => __pbn__OnlyFree != null;
    public void ResetOnlyFree() => __pbn__OnlyFree = null;
    private bool? __pbn__OnlyFree;

    [global::ProtoBuf.ProtoMember(20, Name = @"max_price_in_cents")]
    public long MaxPriceInCents
    {
        get => __pbn__MaxPriceInCents.GetValueOrDefault();
        set => __pbn__MaxPriceInCents = value;
    }
    public bool ShouldSerializeMaxPriceInCents() => __pbn__MaxPriceInCents != null;
    public void ResetMaxPriceInCents() => __pbn__MaxPriceInCents = null;
    private long? __pbn__MaxPriceInCents;

    [global::ProtoBuf.ProtoMember(21, Name = @"min_discount_percent")]
    public int MinDiscountPercent
    {
        get => __pbn__MinDiscountPercent.GetValueOrDefault();
        set => __pbn__MinDiscountPercent = value;
    }
    public bool ShouldSerializeMinDiscountPercent() => __pbn__MinDiscountPercent != null;
    public void ResetMinDiscountPercent() => __pbn__MinDiscountPercent = null;
    private int? __pbn__MinDiscountPercent;

    [global::ProtoBuf.ProtoMember(22, Name = @"exclude_types")]
    public CWishlistFiltersExcludeTypeFilters ExcludeTypes { get; set; }

    [global::ProtoBuf.ProtoMember(23, Name = @"steam_deck_filters")]
    public CWishlistFiltersSteamDeckFilters SteamDeckFilters { get; set; }

}

[global::ProtoBuf.ProtoContract(Name = @"CWishlistFilters_ExcludeTypeFilters")]
public partial class CWishlistFiltersExcludeTypeFilters : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"exclude_early_access")]
    public bool ExcludeEarlyAccess
    {
        get => __pbn__ExcludeEarlyAccess.GetValueOrDefault();
        set => __pbn__ExcludeEarlyAccess = value;
    }
    public bool ShouldSerializeExcludeEarlyAccess() => __pbn__ExcludeEarlyAccess != null;
    public void ResetExcludeEarlyAccess() => __pbn__ExcludeEarlyAccess = null;
    private bool? __pbn__ExcludeEarlyAccess;

    [global::ProtoBuf.ProtoMember(2, Name = @"exclude_coming_soon")]
    public bool ExcludeComingSoon
    {
        get => __pbn__ExcludeComingSoon.GetValueOrDefault();
        set => __pbn__ExcludeComingSoon = value;
    }
    public bool ShouldSerializeExcludeComingSoon() => __pbn__ExcludeComingSoon != null;
    public void ResetExcludeComingSoon() => __pbn__ExcludeComingSoon = null;
    private bool? __pbn__ExcludeComingSoon;

    [global::ProtoBuf.ProtoMember(3, Name = @"exclude_vr_only")]
    public bool ExcludeVrOnly
    {
        get => __pbn__ExcludeVrOnly.GetValueOrDefault();
        set => __pbn__ExcludeVrOnly = value;
    }
    public bool ShouldSerializeExcludeVrOnly() => __pbn__ExcludeVrOnly != null;
    public void ResetExcludeVrOnly() => __pbn__ExcludeVrOnly = null;
    private bool? __pbn__ExcludeVrOnly;

}

[global::ProtoBuf.ProtoContract(Name = @"CWishlistFilters_SteamDeckFilters")]
public partial class CWishlistFiltersSteamDeckFilters : global::ProtoBuf.IExtensible
{
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"include_verified")]
    public bool IncludeVerified
    {
        get => __pbn__IncludeVerified.GetValueOrDefault();
        set => __pbn__IncludeVerified = value;
    }
    public bool ShouldSerializeIncludeVerified() => __pbn__IncludeVerified != null;
    public void ResetIncludeVerified() => __pbn__IncludeVerified = null;
    private bool? __pbn__IncludeVerified;

    [global::ProtoBuf.ProtoMember(2, Name = @"include_playable")]
    public bool IncludePlayable
    {
        get => __pbn__IncludePlayable.GetValueOrDefault();
        set => __pbn__IncludePlayable = value;
    }
    public bool ShouldSerializeIncludePlayable() => __pbn__IncludePlayable != null;
    public void ResetIncludePlayable() => __pbn__IncludePlayable = null;
    private bool? __pbn__IncludePlayable;

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
